name: x86-linux

on:
  workflow_dispatch:
  push:
    branches: [ "master", "dev" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install packages
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build --yes
 
    - name: Configure CMake
      working-directory: ./examples
      run: cmake . -B build --preset gcc -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ./examples
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Run simple example
      working-directory: ./examples
      run: ./build/run_simple

    - name: Run punctured decoder example 
      working-directory: ./examples
      run: ./build/run_punctured_decoder

    - name: Run tests
      working-directory: ./examples
      run: ./build/run_tests