name: x86-linux

on:
  push:
    branches: [ "master", "dev" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install packages
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build --yes
 
    - name: Configure CMake
      working-directory: ./examples
      run: cmake -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ 

    - name: Build
      working-directory: ./examples
      run: ninja -C ./build

    - name: Run test 
      working-directory: ./examples
      run: ./build/run_tests